SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{60569780DE4EE17A}" {
   m_aEntities {
    SCR_EntityCatalogEntry "{6484BA2451EAD6CE}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6484EB5D58547F8C}" {
     m_bEnabled 0
    }
   }
  }
 }
}