SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{60569780DE4EE17A}" {
   m_aEntities {
    SCR_EntityCatalogEntry "{6484BA2451EAD6CE}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{6484EB5D58547F8C}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{63293C72282D828D}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{63293C7240FEA2EA}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{63293C7241B8F920}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{63293C724124DA88}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{63293C724EBEED48}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{63293C724E338166}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{63293C724FBCDA36}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{63293C724F3E299D}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{63293C724CBBDEF3}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{63293C724C20B18B}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{63293C724DBB8C96}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{63293C724D7E8CEE}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{64F45720EF68DC49}" {
    }
    SCR_EntityCatalogEntry "{64F059F166A387A6}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{64F059F09C7FCC69}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{64F059F09F5F66E6}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{64621AEFB0BB1287}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{64621AEFA107D938}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{64621AE131728A01}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{64621AE1362ACD21}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{64621AEFA9ADFD66}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{64621AEFA8E868E4}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogEntry "{64621AE124215E06}" {
     m_bEnabled 0
    }
   }
  }
 }
}